### ISSUE TITLE
Java Build in VS Code complains about missing bazel

### ISSUE THREAD

**Issue by lbovet** [enola-dev/enola#544]
## Expected Behavior

IDE Build works out of the box after successful `./test.bash`

## Actual Behavior

Somewhere in the IDE Java logs, I see complains because bazel is not in the PATH.

## Workaround

Create a `bazel` symlink to `bazelisk`

## Specifications

- Version: 2ce7768f42d2aee2cee8c9cfe82db96deca99387
- Platform: Ubuntu 20.04

**Comment by vorburger** [comment]
@lbovet thanks for reporting this! Yeah, I know about this, and [previously discussed](https://github.com/salesforce/bazel-vscode-java/issues?q=bazelisk+author%3Avorburger+) this with @guw.  

So the `bazel-vscode-java` VSC extension assumes that a `bazel` executable is available on `PATH`. And the [tools/go/install.bash](https://github.com/enola-dev/enola/blob/2ce7768f42d2aee2cee8c9cfe82db96deca99387/tools/go/install.bash#L25) script of this project attempts to do that by installing if it's not available. What could this project do better to "fix" that? How would you fix this - in a perfect world? Ideas, requesting feedback:

1. Should an existing script of this project (e.g. our `./test.bash`, probably?) whine/complain/abort IFF `$(go env GOPATH)/bin` is not on the `$PATH`, is that perhaps a better "UX" than that script siltently doing that for itself only, so that contributors (YOU) can adjust [your personal dotfiles](https://github.com/vorburger/vorburger-dotfiles-bin-etc) as you see fit - as technically [we're supposed](https://go.dev/doc/install) to when using Go? (But I **_do_** understand that you don't want to "use Go" but "just build this project" - and really would like to make this as simple as possible!)
 
1. Should there be an `./vsc` launcher script in this project, which adds `$(go env GOPATH)/bin` to the `$PATH` if its not already?

PS: By "IDE" you presumably mean VSC? Not [another one](https://docs.enola.dev/dev/ide/#other)? 🤣

**Comment by lbovet** [comment]
I don't have a strong opinion how it should solved. For some reason I had bazelisk but not the bazel symlink, maybe something changed in the meantime. I see that a pristine install would actually work
Maybe we could check for bazel instead of bazelisk to perform the install
I close it here because it was a specific issue depending on recent changes
