### ISSUE TITLE
VSC integration and ./enola script should "just work" using the same JDK which Bazel downloaded and runs the build / tests under

### ISSUE THREAD

**Issue by lbovet** [enola-dev/enola#546]
## Expected Behavior

Code should rely 100% on specified APIs.

## Actual Behavior

Ugly dependency to internal com.sun classes. I cannot build with the provided JDK installed by Bazel.

- Version: 2ce7768f42d2aee2cee8c9cfe82db96deca99387
- Platform: Ubuntu 20.04

**Comment by vorburger** [comment]
@lbovet thanks for reporting this! I'm unfortunately not sure what exactly you mean by this... may I request more details?

Which dependency to what unknown class in which source? Can you copy/paste some error message? )Or even Screenshot?)

**Comment by lbovet** [comment]
com.sun.net.httpserver
But I just searched and it seems to be a standard API. For some reason this package is not found in my install
Investigating further...

**Comment by lbovet** [comment]
Looks like it would require to include the module [jdk.httpserver](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.httpserver/module-summary.html) but I have no idea how to do that with bazel.

**Comment by vorburger** [comment]
Oh, god! Why are dependencies always such a mess! 😵‍💫 

> Looks like it would require to include the module [jdk.httpserver](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.httpserver/module-summary.html) but I have no idea how to do that with bazel.

I don't think that's possible or what would help. What's likely going on here is that I've configured Bazel to use "the host's Java environment". And for SOME reason, your local Java OS package (?) doesn't have this module... does Debian package individual JDK (21) modules as separate DEB packages?! But Bazel CAN also have a dependency to a fixed "remote" JDK and download and build with that. It actually originally used to be like that here, and then I changed it. I think seeing this makes me change my mind (again) - let me do something (right now) to just make Bazel download and use a "good" JDK that we know works to build this project - that seems easier, after all.

**Comment by vorburger** [comment]
> make Bazel download and use a "good" JDK that we know works to build this project 

Wait, I'm confused - the project IS ALREADY [configured](https://github.com/enola-dev/enola/blob/cfa1cdd232d6ef1b2ee34bfa1901fcbd04a64f8d/.bazelrc#L8) to do this like so, as-is right now!

Except... I am so stupid, and set `--java_runtime_version=` as well as `--tool_java_runtime_version` TWICE, once as `21` (which means "your local JDK" - I think) and before that as `remotejdk_21` (which means "use one that Bazel will DL") - that's probably not very smart... 🤣 I wonder if #549 will fix this problem, for you? (Was it build `javac` failures, or test execution failures?)

@lbovet would you be willing to post an exact error message? Like some output you get e.g. from `./test.bash` with Bazel failures.

**Comment by lbovet** [comment]
Bazel installs a JDK 21. I have put it in the PATH so that we have only one JDK used for the project:
Thus, the java command used buy the IDE build is `/home/<username>/.cache/bazel/_bazel_<username>/install/<hash>/embedded_tools/jdk/bin/java`
Apparently, this JDK does not have the jdk.httpserver module built-in, hence the problem.
We I run  `java --list-modules`, I don't see it. Can you see it?
I am very far from having any skills in this area...

**Comment by vorburger** [comment]
> The fix does not help.

So you git pull and have #549 now? OK.

Hm. Sorry but just to clarify what exactly we are actually chasing down here:

* Is `./test.bash` working for you? Fully - does it complete successfully? Just to understand if the Bazel build works on CLI, for you. If that doesn't work, we should perhaps make sure that works, first.

* When that works, are you reporting here that you have red in VSC? "Just" in that `web/sun/src/main/java/dev/enola/web/sun/SunServer.java` due to the `import com.sun.net.httpserver` - or also elsewhere? Is that the only problem left?

> /home/<username>/.cache/bazel/_bazel_<username>/install/<hash>/embedded_tools/jdk/bin/java
> I have put it in the PATH so that we have only one JDK used for the project:

Nice idea! (Although that "hash" may change, of course.)

> Apparently, this JDK does not have the jdk.httpserver module built-in, hence the problem.

That's interesting! And surprising me (because I interpret [this documentation](https://bazel.build/docs/bazel-and-java#java-versions) as meaning that [this line](https://github.com/enola-dev/enola/blob/68ea6ffdc110a0e6d0533a0d5e6f0debf8cb06c7/.bazelrc#L12) is causing the test to run under the JDK 21 which Bazel downloads). 

Assuming (see above) that CLI works for you, and you "just" have an in-VSC-IDE problem, could you please try to see what happens if you run (just) this on the CLI, to see if [`web/sun/src/test/java/dev/enola/web/sun/test/SunServerTest.java`](https://github.com/enola-dev/enola/blob/68ea6ffdc110a0e6d0533a0d5e6f0debf8cb06c7/web/sun/src/test/java/dev/enola/web/sun/test/SunServerTest.java#L1) passes:

    bazelisk test //web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest

> When I run java --list-modules, I don't see it. Can you see it?

Here is some of my output - first using the JDK that I have installed via OS package in my Fedora workstation:

```bash
$ which java
/usr/bin/java

$ java -version
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (Red_Hat-21.0.2.0.13-1) (build 21.0.2+13)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.2.0.13-1) (build 21.0.2+13, mixed mode, sharing)

$ java --list-modules | wc --lines
69

$ java --list-modules | grep jdk.httpserver
jdk.httpserver@21.0.2
```

and now similarly using the one that Bazel DL'd, like you:

```bash
$  ~/.cache/bazel/_bazel_vorburger/install/14fb027596f626f2526df4873ea20b8b/embedded_tools/jdk/bin/java -version
openjdk 21 2023-09-19
OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35)
OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode)

$ ~/.cache/bazel/_bazel_vorburger/install/14fb027596f626f2526df4873ea20b8b/embedded_tools/jdk/bin/java --list-modules | wc --lines
13

$ ~/.cache/bazel/_bazel_vorburger/install/14fb027596f626f2526df4873ea20b8b/embedded_tools/jdk/bin/java --list-modules
NADA | grep jdk.httpserver
```

Looks like you're right... 🍭  That `SunServerTest` must be running using my `/usr/bin/java`?! I'll uninstall it, and see if I can make Bazel run tests with the JDK it DL.

**Comment by vorburger** [comment]
> Looks like you're right... 🍭 That SunServerTest must be running using my /usr/bin/java?!
> I'll uninstall it, and see if I can make Bazel run tests with the JDK it DL.

```bash
$ killall java
$ sudo dnf remove "java-*"
$ bazelisk test //web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest

WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
INFO: Analyzed target //web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest (117 packages loaded, 4072 targets configured).
INFO: Found 1 test target...
Target //web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest up-to-date:
  bazel-bin/web/sun/src/test/java/dev/enola/web/sun/test/SunServerTest
  bazel-bin/web/sun/src/test/java/dev/enola/web/sun/test/SunServerTest.jar
INFO: Elapsed time: 9.070s, Critical Path: 4.88s
INFO: 42 processes: 3 internal, 32 linux-sandbox, 7 worker.
INFO: Build completed successfully, 42 total actions
//web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest             PASSED in 0.8s

Executed 1 out of 1 test: 1 test passes.
```

Now this is curious...

**Comment by vorburger** [comment]
JUST to be extra sure and careful with this wonderful _[{ Fast, Correct } — Choose two](https://bazel.build/install)_ Build tool:

```bash
$ killall java
$ sudo rm -rf ~/.cache/bazel/
$ bazelisk test //web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest
```

but it STILL does work for me, as-is. Very weird!

But [this](https://github.com/enola-dev/enola/blob/68ea6ffdc110a0e6d0533a0d5e6f0debf8cb06c7/.bazelrc#L5C28-L5C37) seems wrong... I'll try to remove it. Without being able to reproduce it, I've no idea if that will help.

**Comment by vorburger** [comment]
> Hm. Sorry but just to clarify what exactly we are actually chasing down here:

@lbovet has clarified by DM that `bazelisk test //web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest` also does work for him.

So this not a _"Bazel CLI build issue",_ but a _"Bazel in/or VSC integration"_ issue. I've update the issue title accordingly.

**Comment by vorburger** [comment]
We have now figured out the root cause of the problem:

If one uses the `~/.cache/bazel/_bazel_$USER/install/<hash>/embedded_tools/jdk/bin/java`, then the problem described in this issue (with some confusion...) occurs: VSC cannot find the `jdk.httpserver` Java Module where `com.sun.net.httpserver`.

If however one uses `~/.cache/bazel/_bazel_$USER/<hash>/external/remotejdk21_linux/`, then everything works just fine.

In a perfect world, everything should "just work out of the box". For this, ideally `./enola` should run `java` from that `remotejdk21_linux`. And we could (should) have some start-up (say ... `./env` ?) which sets `PATH` (and `JAVA_HOME` perhaps?) to that, so that when one starts (VSC) `code`, it just works. (Although that probably won't work for/in GitHub Codespaces - but one step at a time.)

I'll post a SO question to learn how to query Bazel for the path to the configured Java Toolchain...

**Comment by vorburger** [comment]
> I'll post a SO question to learn how to query Bazel for the path to the configured Java Toolchain...

https://stackoverflow.com/q/78057833/421602 - @guw do you happen to know how to do this?

**Comment by guw** [comment]
https://github.com/salesforce/bazel-eclipse/blob/888bcd333ac7bd4166fdb411562b74c2b54514d5/bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/discovery/BaseProvisioningStrategy.java#L945-L960

It uses a query file because extracting the information requires a bit more Starlark code.

**Comment by vorburger** [comment]
@guw Thank You! I've tried [that](https://github.com/salesforce/bazel-eclipse/blob/888bcd333ac7bd4166fdb411562b74c2b54514d5/bundles/com.salesforce.bazel.eclipse.core/src/com/salesforce/bazel/eclipse/core/model/discovery/BaseProvisioningStrategy.java#L945-L960) (after also looking at [this](https://github.com/salesforce/bazel-eclipse/blob/4f2a8a2da6d639acf8fc72849db56d2475d461fe/bundles/com.salesforce.bazel.sdk/src/com/salesforce/bazel/sdk/command/BazelCQueryWithStarlarkExpressionCommand.java#L36)) in (draft) PR #558, but running the `tools/bazel-java-tool-chain/bazel-java-tool-chain.bash` from that PR does not quite work yet, as-is that just outputs this (which isn't the "path" I was hoping to get), I don't suppose you happen to immediately see why?

```
java_toolchain_info_source_version=21\njava_toolchain_info_target_version=21\njava_toolchain_info_java_home=external/remotejdk21_linux
java_runtime_info_java_home=external/remotejdk21_linux
```

**Comment by vorburger** [comment]
> You need to tweak the output to suite your needs. :)

PR #558 is now simplified (I've found [this](https://bazel.build/rules/lib/providers/JavaRuntimeInfo), yay!), but what I'm struggling with is that it returns (literally) `external/remotejdk21_linux` - but I would need (e.g.) `/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/remotejdk21_linux` - how does one get that? (I'm imaging you must have solved this somewhere in https://github.com/salesforce/bazel-vscode-java, to obtain the JDK to set on JDT to build the project.)

**Comment by guw** [comment]
```
bazel info output_base
```

Should give you the needed info and can be used in shell scripts.

**Comment by vorburger** [comment]
@guw thanks so much, that helped a lot, and was what I was missing! It allowed me to finish and merge PR #558.

@lbovet this is fixed! 💯
