### ISSUE TITLE
Add a new field Data to Kind in addition to the existing Link and Related fields.

### ISSUE THREAD

**Issue by gabrielh** [enola-dev/enola#75]
## New feature
This Data field is to retrieve data that is not a related entity (Related) or a Link.

details to follow...

**Comment by vorburger** [comment]
That's such a great idea! I wonder how you came up with it... 😄  LOL, #joking.

I will raise a PR to add this (hopefully soon-ish, i.e. "days not weeks").

**Comment by vorburger** [comment]
Whoa... not so fast - re-opening! This doesn't quite work yet as-is. Adding the field was the easy part!

Supporting this "properly" [in connectors](https://docs.enola.dev/use/connector/) is a different story - and (much) more "interesting"...

I'm going to work on this in a few steps. Initially, I am temporarily replacing the `Any` with a `Struct`, because that's much easier, to start with, and to finish an initial first connectors demo.

Then I will try to switch that back - but rely on having a binary `proto` compiled manually by `protoc`.

The final step would be to have something where a user can just specify a `proto` (text) file, and using something like https://github.com/os72/protoc-jar or https://github.com/square/protoparser (or another implementation of the same) does the magic.

**Comment by vorburger** [comment]
#236 makes a start for this. What's still missing is for e.g. the CLI (and future UIs) to re-transform the Any into something more useful; I'll add that in a follow-up PR.

**Comment by vorburger** [comment]
It took a while 😃  but with the merge of #236 this is now implemented! See the _Files changed_ of that PR for details.

#238 is a new issue for _Any data support in File System Repository Connector_ (that's less of a short term priority).

With that, I'm closing this issue. We can track follow-ups in more specific new issues.
